### ISSUE TITLE
WHMCS v7 Support?

### ISSUE THREAD

**Issue by bStyler** [bitpay/whmcs-plugin#43] opened 2017-04-16 09:11 UTC
Hi guys,

I know that an official Bitpay module for WHMCS v7.1 is in the making.

@pieterpoorthuis once mentioned in another issue that it's due for middle April.

Can we can a status update, please?

We'd love continuing Bitpay as our Bitcoin gateway with WHMCS.

Best wishes,

**Comment by pieterpoorthuis** [comment] 2017-04-18 13:00
We've just committed new code that is WHMCS v7 compatible (tested against WHMCS v7.1.2)

You can download the latest code here: https://github.com/bitpay/whmcs-plugin/archive/master.zip

I will create a release next week (provided no issues are found).

**Comment by bStyler** [comment] 2017-04-24 08:22
@pieterpoorthuis Thanks for the exciting update.

1) How things looking 6-7 days after? :) Are there any issues found?
2) Is the plugin also WHMCS v5 compatible of WHMCS v7 only?

**Comment by bStyler** [comment] 2017-04-30 08:07
Bump for @pieterpoorthuis :)

**Comment by pieterpoorthuis** [comment] 2017-05-08 16:14
There were two issues reported around creating invoices (displaying "Invalid invoice id #0"), that I could not reproduce yet.

Therefore I've created a release of the current source. Feedback/issue reports are appreciated.

**Comment by bStyler** [comment] 2017-05-08 16:45
Thanks, @pieterpoorthuis !

**Comment by stefanotto** [comment] 2017-07-29 13:52
As mentioned in #42 I still experience the "Invalid invoice id #0" issue with the latest plugin version

**Closed** 2018-01-23 11:27 UTC
